---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  type: NodePort
  selector:
    app: gameoflife
  ports:
    - nodePort: 31000
      port: 31500
      targetPort: 8080
      protocol: TCP
      name: dbport